declare const enum knowledgearticle_statuscode {
    Proposed = 1,
    Draft = 2,
    NeedsReview = 3,
    InReview = 4,
    Approved = 5,
    Scheduled = 6,
    Published = 7,
    NeedsReview2 = 8,
    Updating = 9,
    Expired = 10,
    Rejected = 11,
    Archived = 12,
    Discarded = 13,
    Rejected2 = 14,
}
