declare namespace Form.account.Main {
    namespace Information {
        namespace Tabs {
            interface Tabrecordwall extends XrmBase.SectionCollectionBase {
                get(name: "tab_recordwall_section_1"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface General extends XrmBase.SectionCollectionBase {
                get(name: "account information"): XrmBase.PageSection;
                get(name: "address"): XrmBase.PageSection;
                get(name: "shipping information"): XrmBase.PageSection;
                get(name: "description"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Details extends XrmBase.SectionCollectionBase {
                get(name: "professional information"): XrmBase.PageSection;
                get(name: "description_2"): XrmBase.PageSection;
                get(name: "billing information"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Contacts extends XrmBase.SectionCollectionBase {
                get(name: "contacts"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface NotesAndActivities extends XrmBase.SectionCollectionBase {
                get(name: "activities"): XrmBase.PageSection;
                get(name: "notes"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Administration extends XrmBase.SectionCollectionBase {
                get(name: "internal information"): XrmBase.PageSection;
                get(name: "contact methods"): XrmBase.PageSection;
                get(name: "marketing information"): XrmBase.PageSection;
                get(name: "service preferences"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
        }
        interface Attributes extends XrmBase.AttributeCollectionBase {
            get(name: "accountcategorycode"): XrmBase.OptionSetAttribute<account_accountcategorycode>;
            get(name: "accountnumber"): XrmBase.StringAttribute;
            get(name: "address1_addresstypecode"): XrmBase.OptionSetAttribute<account_address1_addresstypecode>;
            get(name: "address1_city"): XrmBase.StringAttribute;
            get(name: "address1_country"): XrmBase.StringAttribute;
            get(name: "address1_freighttermscode"): XrmBase.OptionSetAttribute<account_address1_freighttermscode>;
            get(name: "address1_line1"): XrmBase.StringAttribute;
            get(name: "address1_line2"): XrmBase.StringAttribute;
            get(name: "address1_line3"): XrmBase.StringAttribute;
            get(name: "address1_name"): XrmBase.StringAttribute;
            get(name: "address1_postalcode"): XrmBase.StringAttribute;
            get(name: "address1_shippingmethodcode"): XrmBase.OptionSetAttribute<account_address1_shippingmethodcode>;
            get(name: "address1_stateorprovince"): XrmBase.StringAttribute;
            get(name: "address1_telephone1"): XrmBase.StringAttribute;
            get(name: "creditlimit"): XrmBase.NumberAttribute;
            get(name: "creditonhold"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "customertypecode"): XrmBase.OptionSetAttribute<account_customertypecode>;
            get(name: "defaultpricelevelid"): XrmBase.LookupAttribute<"pricelevel">;
            get(name: "description"): XrmBase.StringAttribute;
            get(name: "donotbulkemail"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotemail"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotfax"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotphone"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotpostalmail"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotsendmm"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "emailaddress1"): XrmBase.StringAttribute;
            get(name: "fax"): XrmBase.StringAttribute;
            get(name: "followemail"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "industrycode"): XrmBase.OptionSetAttribute<account_industrycode>;
            get(name: "lastusedincampaign"): XrmBase.DateAttribute;
            get(name: "name"): XrmBase.StringAttribute;
            get(name: "numberofemployees"): XrmBase.NumberAttribute;
            get(name: "originatingleadid"): XrmBase.LookupAttribute<"lead">;
            get(name: "ownerid"): XrmBase.LookupAttribute<"systemuser" | "team">;
            get(name: "ownershipcode"): XrmBase.OptionSetAttribute<account_ownershipcode>;
            get(name: "parentaccountid"): XrmBase.LookupAttribute<"account">;
            get(name: "paymenttermscode"): XrmBase.OptionSetAttribute<account_paymenttermscode>;
            get(name: "preferredappointmentdaycode"): XrmBase.OptionSetAttribute<account_preferredappointmentdaycode>;
            get(name: "preferredappointmenttimecode"): XrmBase.OptionSetAttribute<account_preferredappointmenttimecode>;
            get(name: "preferredcontactmethodcode"): XrmBase.OptionSetAttribute<account_preferredcontactmethodcode>;
            get(name: "preferredsystemuserid"): XrmBase.LookupAttribute<"systemuser">;
            get(name: "primarycontactid"): XrmBase.LookupAttribute<"contact">;
            get(name: "revenue"): XrmBase.NumberAttribute;
            get(name: "sic"): XrmBase.StringAttribute;
            get(name: "telephone1"): XrmBase.StringAttribute;
            get(name: "telephone2"): XrmBase.StringAttribute;
            get(name: "territoryid"): XrmBase.LookupAttribute<"territory">;
            get(name: "tickersymbol"): XrmBase.StringAttribute;
            get(name: "transactioncurrencyid"): XrmBase.LookupAttribute<"transactioncurrency">;
            get(name: "websiteurl"): XrmBase.StringAttribute;
            get(name: string): undefined;
            get(): XrmBase.Attribute<any>[];
            get(index: number): XrmBase.Attribute<any>;
            get(chooser: (item: XrmBase.Attribute<any>, index: number) => boolean): XrmBase.Attribute<any>[];
        }
        interface Controls extends XrmBase.ControlCollectionBase {
            get(name: "accountactivitiesgrid"): XrmBase.SubGridControl<"activitypointer">;
            get(name: "accountcategorycode"): XrmBase.OptionSetControl<account_accountcategorycode>;
            get(name: "accountContactsGrid"): XrmBase.SubGridControl<"contact">;
            get(name: "accountnumber"): XrmBase.StringControl;
            get(name: "address1_addresstypecode"): XrmBase.OptionSetControl<account_address1_addresstypecode>;
            get(name: "address1_city"): XrmBase.StringControl;
            get(name: "address1_country"): XrmBase.StringControl;
            get(name: "address1_freighttermscode"): XrmBase.OptionSetControl<account_address1_freighttermscode>;
            get(name: "address1_line1"): XrmBase.StringControl;
            get(name: "address1_line2"): XrmBase.StringControl;
            get(name: "address1_line3"): XrmBase.StringControl;
            get(name: "address1_name"): XrmBase.StringControl;
            get(name: "address1_postalcode"): XrmBase.StringControl;
            get(name: "address1_shippingmethodcode"): XrmBase.OptionSetControl<account_address1_shippingmethodcode>;
            get(name: "address1_stateorprovince"): XrmBase.StringControl;
            get(name: "address1_telephone1"): XrmBase.StringControl;
            get(name: "creditlimit"): XrmBase.NumberControl;
            get(name: "creditonhold"): XrmBase.OptionSetControl<any>;
            get(name: "customertypecode"): XrmBase.OptionSetControl<account_customertypecode>;
            get(name: "defaultpricelevelid"): XrmBase.LookupControl<"pricelevel">;
            get(name: "description"): XrmBase.StringControl;
            get(name: "donotbulkemail"): XrmBase.OptionSetControl<any>;
            get(name: "donotemail"): XrmBase.OptionSetControl<any>;
            get(name: "donotfax"): XrmBase.OptionSetControl<any>;
            get(name: "donotphone"): XrmBase.OptionSetControl<any>;
            get(name: "donotpostalmail"): XrmBase.OptionSetControl<any>;
            get(name: "donotsendmm"): XrmBase.OptionSetControl<any>;
            get(name: "emailaddress1"): XrmBase.StringControl;
            get(name: "fax"): XrmBase.StringControl;
            get(name: "followemail"): XrmBase.OptionSetControl<any>;
            get(name: "industrycode"): XrmBase.OptionSetControl<account_industrycode>;
            get(name: "lastusedincampaign"): XrmBase.DateControl;
            get(name: "name"): XrmBase.StringControl;
            get(name: "notescontrol"): XrmBase.StringControl;
            get(name: "numberofemployees"): XrmBase.NumberControl;
            get(name: "originatingleadid"): XrmBase.LookupControl<"lead">;
            get(name: "ownerid"): XrmBase.LookupControl<"systemuser" | "team">;
            get(name: "ownershipcode"): XrmBase.OptionSetControl<account_ownershipcode>;
            get(name: "parentaccountid"): XrmBase.LookupControl<"account">;
            get(name: "paymenttermscode"): XrmBase.OptionSetControl<account_paymenttermscode>;
            get(name: "preferredappointmentdaycode"): XrmBase.OptionSetControl<account_preferredappointmentdaycode>;
            get(name: "preferredappointmenttimecode"): XrmBase.OptionSetControl<account_preferredappointmenttimecode>;
            get(name: "preferredcontactmethodcode"): XrmBase.OptionSetControl<account_preferredcontactmethodcode>;
            get(name: "preferredsystemuserid"): XrmBase.LookupControl<"systemuser">;
            get(name: "primarycontactid"): XrmBase.LookupControl<"contact">;
            get(name: "revenue"): XrmBase.NumberControl;
            get(name: "sic"): XrmBase.StringControl;
            get(name: "telephone1"): XrmBase.StringControl;
            get(name: "telephone2"): XrmBase.StringControl;
            get(name: "territoryid"): XrmBase.LookupControl<"territory">;
            get(name: "tickersymbol"): XrmBase.BaseControl;
            get(name: "transactioncurrencyid"): XrmBase.LookupControl<"transactioncurrency">;
            get(name: "WebResource_RecordWall"): XrmBase.WebResourceControl;
            get(name: "websiteurl"): XrmBase.StringControl;
            get(name: string): undefined;
            get(): XrmBase.BaseControl[];
            get(index: number): XrmBase.BaseControl;
            get(chooser: (item: XrmBase.BaseControl, index: number) => boolean): XrmBase.BaseControl[];
        }
        interface Tabs extends XrmBase.TabCollectionBase {
            get(name: "tab_recordwall"): XrmBase.PageTab<Tabs.Tabrecordwall>;
            get(name: "general"): XrmBase.PageTab<Tabs.General>;
            get(name: "details"): XrmBase.PageTab<Tabs.Details>;
            get(name: "contacts"): XrmBase.PageTab<Tabs.Contacts>;
            get(name: "notes and activities"): XrmBase.PageTab<Tabs.NotesAndActivities>;
            get(name: "administration"): XrmBase.PageTab<Tabs.Administration>;
            get(name: string): undefined;
            get(): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
            get(index: number): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>;
            get(chooser: (item: XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>, index: number) => boolean): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
        }
    }
    interface Information extends XrmBase.PageBase<Information.Attributes, Information.Tabs, Information.Controls> {
        getAttribute(attributeName: "name"): XrmBase.StringAttribute;
        getAttribute(attributeName: "telephone1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "primarycontactid"): XrmBase.LookupAttribute<"contact">;
        getAttribute(attributeName: "telephone2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "accountnumber"): XrmBase.StringAttribute;
        getAttribute(attributeName: "fax"): XrmBase.StringAttribute;
        getAttribute(attributeName: "parentaccountid"): XrmBase.LookupAttribute<"account">;
        getAttribute(attributeName: "websiteurl"): XrmBase.StringAttribute;
        getAttribute(attributeName: "emailaddress1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_addresstypecode"): XrmBase.OptionSetAttribute<account_address1_addresstypecode>;
        getAttribute(attributeName: "address1_city"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_name"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_stateorprovince"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_postalcode"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_country"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line3"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_telephone1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_shippingmethodcode"): XrmBase.OptionSetAttribute<account_address1_shippingmethodcode>;
        getAttribute(attributeName: "address1_freighttermscode"): XrmBase.OptionSetAttribute<account_address1_freighttermscode>;
        getAttribute(attributeName: "description"): XrmBase.StringAttribute;
        getAttribute(attributeName: "industrycode"): XrmBase.OptionSetAttribute<account_industrycode>;
        getAttribute(attributeName: "revenue"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "ownershipcode"): XrmBase.OptionSetAttribute<account_ownershipcode>;
        getAttribute(attributeName: "numberofemployees"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "tickersymbol"): XrmBase.StringAttribute;
        getAttribute(attributeName: "sic"): XrmBase.StringAttribute;
        getAttribute(attributeName: "territoryid"): XrmBase.LookupAttribute<"territory">;
        getAttribute(attributeName: "customertypecode"): XrmBase.OptionSetAttribute<account_customertypecode>;
        getAttribute(attributeName: "accountcategorycode"): XrmBase.OptionSetAttribute<account_accountcategorycode>;
        getAttribute(attributeName: "transactioncurrencyid"): XrmBase.LookupAttribute<"transactioncurrency">;
        getAttribute(attributeName: "paymenttermscode"): XrmBase.OptionSetAttribute<account_paymenttermscode>;
        getAttribute(attributeName: "creditlimit"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "creditonhold"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "defaultpricelevelid"): XrmBase.LookupAttribute<"pricelevel">;
        getAttribute(attributeName: "ownerid"): XrmBase.LookupAttribute<"systemuser" | "team">;
        getAttribute(attributeName: "preferredcontactmethodcode"): XrmBase.OptionSetAttribute<account_preferredcontactmethodcode>;
        getAttribute(attributeName: "donotbulkemail"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotemail"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "followemail"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotpostalmail"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotphone"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotfax"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "originatingleadid"): XrmBase.LookupAttribute<"lead">;
        getAttribute(attributeName: "lastusedincampaign"): XrmBase.DateAttribute;
        getAttribute(attributeName: "donotsendmm"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "preferredappointmentdaycode"): XrmBase.OptionSetAttribute<account_preferredappointmentdaycode>;
        getAttribute(attributeName: "preferredappointmenttimecode"): XrmBase.OptionSetAttribute<account_preferredappointmenttimecode>;
        getAttribute(attributeName: "preferredsystemuserid"): XrmBase.LookupAttribute<"systemuser">;
        getAttribute(attributeName: string): undefined;
        getControl(controlName: "WebResource_RecordWall"): XrmBase.WebResourceControl;
        getControl(controlName: "name"): XrmBase.StringControl;
        getControl(controlName: "telephone1"): XrmBase.StringControl;
        getControl(controlName: "primarycontactid"): XrmBase.LookupControl<"contact">;
        getControl(controlName: "telephone2"): XrmBase.StringControl;
        getControl(controlName: "accountnumber"): XrmBase.StringControl;
        getControl(controlName: "fax"): XrmBase.StringControl;
        getControl(controlName: "parentaccountid"): XrmBase.LookupControl<"account">;
        getControl(controlName: "websiteurl"): XrmBase.StringControl;
        getControl(controlName: "emailaddress1"): XrmBase.StringControl;
        getControl(controlName: "address1_addresstypecode"): XrmBase.OptionSetControl<account_address1_addresstypecode>;
        getControl(controlName: "address1_city"): XrmBase.StringControl;
        getControl(controlName: "address1_name"): XrmBase.StringControl;
        getControl(controlName: "address1_stateorprovince"): XrmBase.StringControl;
        getControl(controlName: "address1_line1"): XrmBase.StringControl;
        getControl(controlName: "address1_postalcode"): XrmBase.StringControl;
        getControl(controlName: "address1_line2"): XrmBase.StringControl;
        getControl(controlName: "address1_country"): XrmBase.StringControl;
        getControl(controlName: "address1_line3"): XrmBase.StringControl;
        getControl(controlName: "address1_telephone1"): XrmBase.StringControl;
        getControl(controlName: "address1_shippingmethodcode"): XrmBase.OptionSetControl<account_address1_shippingmethodcode>;
        getControl(controlName: "address1_freighttermscode"): XrmBase.OptionSetControl<account_address1_freighttermscode>;
        getControl(controlName: "description"): XrmBase.StringControl;
        getControl(controlName: "industrycode"): XrmBase.OptionSetControl<account_industrycode>;
        getControl(controlName: "revenue"): XrmBase.NumberControl;
        getControl(controlName: "ownershipcode"): XrmBase.OptionSetControl<account_ownershipcode>;
        getControl(controlName: "numberofemployees"): XrmBase.NumberControl;
        getControl(controlName: "tickersymbol"): XrmBase.BaseControl;
        getControl(controlName: "sic"): XrmBase.StringControl;
        getControl(controlName: "territoryid"): XrmBase.LookupControl<"territory">;
        getControl(controlName: "customertypecode"): XrmBase.OptionSetControl<account_customertypecode>;
        getControl(controlName: "accountcategorycode"): XrmBase.OptionSetControl<account_accountcategorycode>;
        getControl(controlName: "transactioncurrencyid"): XrmBase.LookupControl<"transactioncurrency">;
        getControl(controlName: "paymenttermscode"): XrmBase.OptionSetControl<account_paymenttermscode>;
        getControl(controlName: "creditlimit"): XrmBase.NumberControl;
        getControl(controlName: "creditonhold"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "defaultpricelevelid"): XrmBase.LookupControl<"pricelevel">;
        getControl(controlName: "accountContactsGrid"): XrmBase.SubGridControl<"contact">;
        getControl(controlName: "accountactivitiesgrid"): XrmBase.SubGridControl<"activitypointer">;
        getControl(controlName: "notescontrol"): XrmBase.StringControl;
        getControl(controlName: "ownerid"): XrmBase.LookupControl<"systemuser" | "team">;
        getControl(controlName: "preferredcontactmethodcode"): XrmBase.OptionSetControl<account_preferredcontactmethodcode>;
        getControl(controlName: "donotbulkemail"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotemail"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "followemail"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotpostalmail"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotphone"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotfax"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "originatingleadid"): XrmBase.LookupControl<"lead">;
        getControl(controlName: "lastusedincampaign"): XrmBase.DateControl;
        getControl(controlName: "donotsendmm"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "preferredappointmentdaycode"): XrmBase.OptionSetControl<account_preferredappointmentdaycode>;
        getControl(controlName: "preferredappointmenttimecode"): XrmBase.OptionSetControl<account_preferredappointmenttimecode>;
        getControl(controlName: "preferredsystemuserid"): XrmBase.LookupControl<"systemuser">;
        getControl(controlName: string): undefined;
    }
}
