declare namespace Form.contact.Main {
    namespace Information {
        namespace Tabs {
            interface Tabrecordwall extends XrmBase.SectionCollectionBase {
                get(name: "tab_recordwall_section_1"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface General extends XrmBase.SectionCollectionBase {
                get(name: "name"): XrmBase.PageSection;
                get(name: "address"): XrmBase.PageSection;
                get(name: "shipping information"): XrmBase.PageSection;
                get(name: "description"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Details extends XrmBase.SectionCollectionBase {
                get(name: "professional information"): XrmBase.PageSection;
                get(name: "personal information"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface NotesAndActivities extends XrmBase.SectionCollectionBase {
                get(name: "activities"): XrmBase.PageSection;
                get(name: "notes"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Administration extends XrmBase.SectionCollectionBase {
                get(name: "internal information"): XrmBase.PageSection;
                get(name: "billing information"): XrmBase.PageSection;
                get(name: "contact methods"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Conflictstab extends XrmBase.SectionCollectionBase {
                get(name: "conflictssection"): XrmBase.PageSection;
                get(name: "marketing information"): XrmBase.PageSection;
                get(name: "service preferences"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
        }
        interface Attributes extends XrmBase.AttributeCollectionBase {
            get(name: "accountrolecode"): XrmBase.OptionSetAttribute<contact_accountrolecode>;
            get(name: "address1_addresstypecode"): XrmBase.OptionSetAttribute<contact_address1_addresstypecode>;
            get(name: "address1_city"): XrmBase.StringAttribute;
            get(name: "address1_country"): XrmBase.StringAttribute;
            get(name: "address1_freighttermscode"): XrmBase.OptionSetAttribute<contact_address1_freighttermscode>;
            get(name: "address1_line1"): XrmBase.StringAttribute;
            get(name: "address1_line2"): XrmBase.StringAttribute;
            get(name: "address1_line3"): XrmBase.StringAttribute;
            get(name: "address1_name"): XrmBase.StringAttribute;
            get(name: "address1_postalcode"): XrmBase.StringAttribute;
            get(name: "address1_shippingmethodcode"): XrmBase.OptionSetAttribute<contact_address1_shippingmethodcode>;
            get(name: "address1_stateorprovince"): XrmBase.StringAttribute;
            get(name: "address1_telephone1"): XrmBase.StringAttribute;
            get(name: "anniversary"): XrmBase.DateAttribute;
            get(name: "assistantname"): XrmBase.StringAttribute;
            get(name: "assistantphone"): XrmBase.StringAttribute;
            get(name: "birthdate"): XrmBase.DateAttribute;
            get(name: "creditlimit"): XrmBase.NumberAttribute;
            get(name: "creditonhold"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "defaultpricelevelid"): XrmBase.LookupAttribute<"pricelevel">;
            get(name: "department"): XrmBase.StringAttribute;
            get(name: "description"): XrmBase.StringAttribute;
            get(name: "donotbulkemail"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotemail"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotfax"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotphone"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotpostalmail"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "donotsendmm"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "emailaddress1"): XrmBase.StringAttribute;
            get(name: "familystatuscode"): XrmBase.OptionSetAttribute<contact_familystatuscode>;
            get(name: "fax"): XrmBase.StringAttribute;
            get(name: "firstname"): XrmBase.StringAttribute;
            get(name: "gendercode"): XrmBase.OptionSetAttribute<contact_gendercode>;
            get(name: "jobtitle"): XrmBase.StringAttribute;
            get(name: "lastname"): XrmBase.StringAttribute;
            get(name: "lastusedincampaign"): XrmBase.DateAttribute;
            get(name: "managername"): XrmBase.StringAttribute;
            get(name: "managerphone"): XrmBase.StringAttribute;
            get(name: "middlename"): XrmBase.StringAttribute;
            get(name: "mobilephone"): XrmBase.StringAttribute;
            get(name: "originatingleadid"): XrmBase.LookupAttribute<"lead">;
            get(name: "ownerid"): XrmBase.LookupAttribute<"systemuser" | "team">;
            get(name: "parentcustomerid"): XrmBase.LookupAttribute<"account" | "contact">;
            get(name: "paymenttermscode"): XrmBase.OptionSetAttribute<contact_paymenttermscode>;
            get(name: "preferredappointmentdaycode"): XrmBase.OptionSetAttribute<contact_preferredappointmentdaycode>;
            get(name: "preferredappointmenttimecode"): XrmBase.OptionSetAttribute<contact_preferredappointmenttimecode>;
            get(name: "preferredcontactmethodcode"): XrmBase.OptionSetAttribute<contact_preferredcontactmethodcode>;
            get(name: "preferredequipmentid"): XrmBase.LookupAttribute<"equipment">;
            get(name: "preferredserviceid"): XrmBase.LookupAttribute<"service">;
            get(name: "preferredsystemuserid"): XrmBase.LookupAttribute<"systemuser">;
            get(name: "salutation"): XrmBase.StringAttribute;
            get(name: "spousesname"): XrmBase.StringAttribute;
            get(name: "telephone1"): XrmBase.StringAttribute;
            get(name: "telephone2"): XrmBase.StringAttribute;
            get(name: "transactioncurrencyid"): XrmBase.LookupAttribute<"transactioncurrency">;
            get(name: string): undefined;
            get(): XrmBase.Attribute<any>[];
            get(index: number): XrmBase.Attribute<any>;
            get(chooser: (item: XrmBase.Attribute<any>, index: number) => boolean): XrmBase.Attribute<any>[];
        }
        interface Controls extends XrmBase.ControlCollectionBase {
            get(name: "accountrolecode"): XrmBase.OptionSetControl<contact_accountrolecode>;
            get(name: "address1_addresstypecode"): XrmBase.OptionSetControl<contact_address1_addresstypecode>;
            get(name: "address1_city"): XrmBase.StringControl;
            get(name: "address1_country"): XrmBase.StringControl;
            get(name: "address1_freighttermscode"): XrmBase.OptionSetControl<contact_address1_freighttermscode>;
            get(name: "address1_line1"): XrmBase.StringControl;
            get(name: "address1_line2"): XrmBase.StringControl;
            get(name: "address1_line3"): XrmBase.StringControl;
            get(name: "address1_name"): XrmBase.StringControl;
            get(name: "address1_postalcode"): XrmBase.StringControl;
            get(name: "address1_shippingmethodcode"): XrmBase.OptionSetControl<contact_address1_shippingmethodcode>;
            get(name: "address1_stateorprovince"): XrmBase.StringControl;
            get(name: "address1_telephone1"): XrmBase.StringControl;
            get(name: "anniversary"): XrmBase.DateControl;
            get(name: "assistantname"): XrmBase.StringControl;
            get(name: "assistantphone"): XrmBase.StringControl;
            get(name: "birthdate"): XrmBase.DateControl;
            get(name: "contactactivitiesgrid"): XrmBase.SubGridControl<"activitypointer">;
            get(name: "creditlimit"): XrmBase.NumberControl;
            get(name: "creditonhold"): XrmBase.OptionSetControl<any>;
            get(name: "defaultpricelevelid"): XrmBase.LookupControl<"pricelevel">;
            get(name: "department"): XrmBase.StringControl;
            get(name: "description"): XrmBase.StringControl;
            get(name: "donotbulkemail"): XrmBase.OptionSetControl<any>;
            get(name: "donotemail"): XrmBase.OptionSetControl<any>;
            get(name: "donotfax"): XrmBase.OptionSetControl<any>;
            get(name: "donotphone"): XrmBase.OptionSetControl<any>;
            get(name: "donotpostalmail"): XrmBase.OptionSetControl<any>;
            get(name: "donotsendmm"): XrmBase.OptionSetControl<any>;
            get(name: "emailaddress1"): XrmBase.StringControl;
            get(name: "familystatuscode"): XrmBase.OptionSetControl<contact_familystatuscode>;
            get(name: "fax"): XrmBase.StringControl;
            get(name: "firstname"): XrmBase.StringControl;
            get(name: "gendercode"): XrmBase.OptionSetControl<contact_gendercode>;
            get(name: "jobtitle"): XrmBase.StringControl;
            get(name: "lastname"): XrmBase.StringControl;
            get(name: "lastusedincampaign"): XrmBase.DateControl;
            get(name: "managername"): XrmBase.StringControl;
            get(name: "managerphone"): XrmBase.StringControl;
            get(name: "middlename"): XrmBase.StringControl;
            get(name: "mobilephone"): XrmBase.StringControl;
            get(name: "notescontrol"): XrmBase.StringControl;
            get(name: "originatingleadid"): XrmBase.LookupControl<"lead">;
            get(name: "ownerid"): XrmBase.LookupControl<"systemuser" | "team">;
            get(name: "parentcustomerid"): XrmBase.LookupControl<"account" | "contact">;
            get(name: "paymenttermscode"): XrmBase.OptionSetControl<contact_paymenttermscode>;
            get(name: "preferredappointmentdaycode"): XrmBase.OptionSetControl<contact_preferredappointmentdaycode>;
            get(name: "preferredappointmenttimecode"): XrmBase.OptionSetControl<contact_preferredappointmenttimecode>;
            get(name: "preferredcontactmethodcode"): XrmBase.OptionSetControl<contact_preferredcontactmethodcode>;
            get(name: "preferredequipmentid"): XrmBase.LookupControl<"equipment">;
            get(name: "preferredserviceid"): XrmBase.LookupControl<"service">;
            get(name: "preferredsystemuserid"): XrmBase.LookupControl<"systemuser">;
            get(name: "salutation"): XrmBase.StringControl;
            get(name: "spousesname"): XrmBase.StringControl;
            get(name: "telephone1"): XrmBase.StringControl;
            get(name: "telephone2"): XrmBase.StringControl;
            get(name: "transactioncurrencyid"): XrmBase.LookupControl<"transactioncurrency">;
            get(name: "WebResource_RecordWall"): XrmBase.WebResourceControl;
            get(name: string): undefined;
            get(): XrmBase.BaseControl[];
            get(index: number): XrmBase.BaseControl;
            get(chooser: (item: XrmBase.BaseControl, index: number) => boolean): XrmBase.BaseControl[];
        }
        interface Tabs extends XrmBase.TabCollectionBase {
            get(name: "tab_recordwall"): XrmBase.PageTab<Tabs.Tabrecordwall>;
            get(name: "general"): XrmBase.PageTab<Tabs.General>;
            get(name: "details"): XrmBase.PageTab<Tabs.Details>;
            get(name: "notes and activities"): XrmBase.PageTab<Tabs.NotesAndActivities>;
            get(name: "administration"): XrmBase.PageTab<Tabs.Administration>;
            get(name: "conflictstab"): XrmBase.PageTab<Tabs.Conflictstab>;
            get(name: string): undefined;
            get(): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
            get(index: number): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>;
            get(chooser: (item: XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>, index: number) => boolean): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
        }
    }
    interface Information extends XrmBase.PageBase<Information.Attributes, Information.Tabs, Information.Controls> {
        getAttribute(attributeName: "salutation"): XrmBase.StringAttribute;
        getAttribute(attributeName: "telephone1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "firstname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "telephone2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "middlename"): XrmBase.StringAttribute;
        getAttribute(attributeName: "mobilephone"): XrmBase.StringAttribute;
        getAttribute(attributeName: "lastname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "fax"): XrmBase.StringAttribute;
        getAttribute(attributeName: "jobtitle"): XrmBase.StringAttribute;
        getAttribute(attributeName: "emailaddress1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "parentcustomerid"): XrmBase.LookupAttribute<"account" | "contact">;
        getAttribute(attributeName: "address1_addresstypecode"): XrmBase.OptionSetAttribute<contact_address1_addresstypecode>;
        getAttribute(attributeName: "address1_city"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_name"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_stateorprovince"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_postalcode"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_country"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line3"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_telephone1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_freighttermscode"): XrmBase.OptionSetAttribute<contact_address1_freighttermscode>;
        getAttribute(attributeName: "address1_shippingmethodcode"): XrmBase.OptionSetAttribute<contact_address1_shippingmethodcode>;
        getAttribute(attributeName: "description"): XrmBase.StringAttribute;
        getAttribute(attributeName: "department"): XrmBase.StringAttribute;
        getAttribute(attributeName: "accountrolecode"): XrmBase.OptionSetAttribute<contact_accountrolecode>;
        getAttribute(attributeName: "managername"): XrmBase.StringAttribute;
        getAttribute(attributeName: "assistantname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "managerphone"): XrmBase.StringAttribute;
        getAttribute(attributeName: "assistantphone"): XrmBase.StringAttribute;
        getAttribute(attributeName: "gendercode"): XrmBase.OptionSetAttribute<contact_gendercode>;
        getAttribute(attributeName: "birthdate"): XrmBase.DateAttribute;
        getAttribute(attributeName: "familystatuscode"): XrmBase.OptionSetAttribute<contact_familystatuscode>;
        getAttribute(attributeName: "anniversary"): XrmBase.DateAttribute;
        getAttribute(attributeName: "spousesname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "ownerid"): XrmBase.LookupAttribute<"systemuser" | "team">;
        getAttribute(attributeName: "transactioncurrencyid"): XrmBase.LookupAttribute<"transactioncurrency">;
        getAttribute(attributeName: "paymenttermscode"): XrmBase.OptionSetAttribute<contact_paymenttermscode>;
        getAttribute(attributeName: "creditlimit"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "creditonhold"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "preferredcontactmethodcode"): XrmBase.OptionSetAttribute<contact_preferredcontactmethodcode>;
        getAttribute(attributeName: "donotbulkemail"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotemail"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotfax"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotphone"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "donotpostalmail"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "defaultpricelevelid"): XrmBase.LookupAttribute<"pricelevel">;
        getAttribute(attributeName: "originatingleadid"): XrmBase.LookupAttribute<"lead">;
        getAttribute(attributeName: "lastusedincampaign"): XrmBase.DateAttribute;
        getAttribute(attributeName: "donotsendmm"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "preferredappointmentdaycode"): XrmBase.OptionSetAttribute<contact_preferredappointmentdaycode>;
        getAttribute(attributeName: "preferredequipmentid"): XrmBase.LookupAttribute<"equipment">;
        getAttribute(attributeName: "preferredappointmenttimecode"): XrmBase.OptionSetAttribute<contact_preferredappointmenttimecode>;
        getAttribute(attributeName: "preferredsystemuserid"): XrmBase.LookupAttribute<"systemuser">;
        getAttribute(attributeName: "preferredserviceid"): XrmBase.LookupAttribute<"service">;
        getAttribute(attributeName: string): undefined;
        getControl(controlName: "WebResource_RecordWall"): XrmBase.WebResourceControl;
        getControl(controlName: "salutation"): XrmBase.StringControl;
        getControl(controlName: "telephone1"): XrmBase.StringControl;
        getControl(controlName: "firstname"): XrmBase.StringControl;
        getControl(controlName: "telephone2"): XrmBase.StringControl;
        getControl(controlName: "middlename"): XrmBase.StringControl;
        getControl(controlName: "mobilephone"): XrmBase.StringControl;
        getControl(controlName: "lastname"): XrmBase.StringControl;
        getControl(controlName: "fax"): XrmBase.StringControl;
        getControl(controlName: "jobtitle"): XrmBase.StringControl;
        getControl(controlName: "emailaddress1"): XrmBase.StringControl;
        getControl(controlName: "parentcustomerid"): XrmBase.LookupControl<"account" | "contact">;
        getControl(controlName: "address1_addresstypecode"): XrmBase.OptionSetControl<contact_address1_addresstypecode>;
        getControl(controlName: "address1_city"): XrmBase.StringControl;
        getControl(controlName: "address1_name"): XrmBase.StringControl;
        getControl(controlName: "address1_stateorprovince"): XrmBase.StringControl;
        getControl(controlName: "address1_line1"): XrmBase.StringControl;
        getControl(controlName: "address1_postalcode"): XrmBase.StringControl;
        getControl(controlName: "address1_line2"): XrmBase.StringControl;
        getControl(controlName: "address1_country"): XrmBase.StringControl;
        getControl(controlName: "address1_line3"): XrmBase.StringControl;
        getControl(controlName: "address1_telephone1"): XrmBase.StringControl;
        getControl(controlName: "address1_freighttermscode"): XrmBase.OptionSetControl<contact_address1_freighttermscode>;
        getControl(controlName: "address1_shippingmethodcode"): XrmBase.OptionSetControl<contact_address1_shippingmethodcode>;
        getControl(controlName: "description"): XrmBase.StringControl;
        getControl(controlName: "department"): XrmBase.StringControl;
        getControl(controlName: "accountrolecode"): XrmBase.OptionSetControl<contact_accountrolecode>;
        getControl(controlName: "managername"): XrmBase.StringControl;
        getControl(controlName: "assistantname"): XrmBase.StringControl;
        getControl(controlName: "managerphone"): XrmBase.StringControl;
        getControl(controlName: "assistantphone"): XrmBase.StringControl;
        getControl(controlName: "gendercode"): XrmBase.OptionSetControl<contact_gendercode>;
        getControl(controlName: "birthdate"): XrmBase.DateControl;
        getControl(controlName: "familystatuscode"): XrmBase.OptionSetControl<contact_familystatuscode>;
        getControl(controlName: "anniversary"): XrmBase.DateControl;
        getControl(controlName: "spousesname"): XrmBase.StringControl;
        getControl(controlName: "contactactivitiesgrid"): XrmBase.SubGridControl<"activitypointer">;
        getControl(controlName: "notescontrol"): XrmBase.StringControl;
        getControl(controlName: "ownerid"): XrmBase.LookupControl<"systemuser" | "team">;
        getControl(controlName: "transactioncurrencyid"): XrmBase.LookupControl<"transactioncurrency">;
        getControl(controlName: "paymenttermscode"): XrmBase.OptionSetControl<contact_paymenttermscode>;
        getControl(controlName: "creditlimit"): XrmBase.NumberControl;
        getControl(controlName: "creditonhold"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "preferredcontactmethodcode"): XrmBase.OptionSetControl<contact_preferredcontactmethodcode>;
        getControl(controlName: "donotbulkemail"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotemail"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotfax"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotphone"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "donotpostalmail"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "defaultpricelevelid"): XrmBase.LookupControl<"pricelevel">;
        getControl(controlName: "originatingleadid"): XrmBase.LookupControl<"lead">;
        getControl(controlName: "lastusedincampaign"): XrmBase.DateControl;
        getControl(controlName: "donotsendmm"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "preferredappointmentdaycode"): XrmBase.OptionSetControl<contact_preferredappointmentdaycode>;
        getControl(controlName: "preferredequipmentid"): XrmBase.LookupControl<"equipment">;
        getControl(controlName: "preferredappointmenttimecode"): XrmBase.OptionSetControl<contact_preferredappointmenttimecode>;
        getControl(controlName: "preferredsystemuserid"): XrmBase.LookupControl<"systemuser">;
        getControl(controlName: "preferredserviceid"): XrmBase.LookupControl<"service">;
        getControl(controlName: string): undefined;
    }
}
