declare namespace Form.systemuser.Main {
    namespace Information {
        namespace Tabs {
            interface Tabrecordwall extends XrmBase.SectionCollectionBase {
                get(name: "tab_recordwall_section_1"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface General extends XrmBase.SectionCollectionBase {
                get(name: "onpremise account information"): XrmBase.PageSection;
                get(name: "online account information"): XrmBase.PageSection;
                get(name: "user information"): XrmBase.PageSection;
                get(name: "organization information"): XrmBase.PageSection;
                get(name: "email configuration"): XrmBase.PageSection;
                get(name: "administration"): XrmBase.PageSection;
                get(name: "queue selection"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Addresses extends XrmBase.SectionCollectionBase {
                get(name: "mailing address"): XrmBase.PageSection;
                get(name: "other address"): XrmBase.PageSection;
                get(name: "address preference"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
        }
        interface Attributes extends XrmBase.AttributeCollectionBase {
            get(name: "accessmode"): XrmBase.OptionSetAttribute<systemuser_accessmode>;
            get(name: "address1_city"): XrmBase.StringAttribute;
            get(name: "address1_country"): XrmBase.StringAttribute;
            get(name: "address1_fax"): XrmBase.StringAttribute;
            get(name: "address1_line1"): XrmBase.StringAttribute;
            get(name: "address1_line2"): XrmBase.StringAttribute;
            get(name: "address1_line3"): XrmBase.StringAttribute;
            get(name: "address1_postalcode"): XrmBase.StringAttribute;
            get(name: "address1_stateorprovince"): XrmBase.StringAttribute;
            get(name: "address1_telephone1"): XrmBase.StringAttribute;
            get(name: "address1_telephone2"): XrmBase.StringAttribute;
            get(name: "address1_telephone3"): XrmBase.StringAttribute;
            get(name: "address2_city"): XrmBase.StringAttribute;
            get(name: "address2_country"): XrmBase.StringAttribute;
            get(name: "address2_line1"): XrmBase.StringAttribute;
            get(name: "address2_line2"): XrmBase.StringAttribute;
            get(name: "address2_line3"): XrmBase.StringAttribute;
            get(name: "address2_postalcode"): XrmBase.StringAttribute;
            get(name: "address2_stateorprovince"): XrmBase.StringAttribute;
            get(name: "businessunitid"): XrmBase.LookupAttribute<"businessunit">;
            get(name: "caltype"): XrmBase.OptionSetAttribute<systemuser_caltype>;
            get(name: "defaultmailbox"): XrmBase.LookupAttribute<"mailbox">;
            get(name: "domainname"): XrmBase.StringAttribute;
            get(name: "firstname"): XrmBase.StringAttribute;
            get(name: "homephone"): XrmBase.StringAttribute;
            get(name: "internalemailaddress"): XrmBase.StringAttribute;
            get(name: "invitestatuscode"): XrmBase.OptionSetAttribute<systemuser_invitestatuscode>;
            get(name: "lastname"): XrmBase.StringAttribute;
            get(name: "mobilealertemail"): XrmBase.StringAttribute;
            get(name: "mobilephone"): XrmBase.StringAttribute;
            get(name: "parentsystemuserid"): XrmBase.LookupAttribute<"systemuser">;
            get(name: "personalemailaddress"): XrmBase.StringAttribute;
            get(name: "positionid"): XrmBase.LookupAttribute<"position">;
            get(name: "preferredaddresscode"): XrmBase.OptionSetAttribute<systemuser_preferredaddresscode>;
            get(name: "preferredphonecode"): XrmBase.OptionSetAttribute<systemuser_preferredphonecode>;
            get(name: "queueid"): XrmBase.LookupAttribute<"queue">;
            get(name: "siteid"): XrmBase.LookupAttribute<"site">;
            get(name: "territoryid"): XrmBase.LookupAttribute<"territory">;
            get(name: "title"): XrmBase.StringAttribute;
            get(name: "windowsliveid"): XrmBase.StringAttribute;
            get(name: string): undefined;
            get(): XrmBase.Attribute<any>[];
            get(index: number): XrmBase.Attribute<any>;
            get(chooser: (item: XrmBase.Attribute<any>, index: number) => boolean): XrmBase.Attribute<any>[];
        }
        interface Controls extends XrmBase.ControlCollectionBase {
            get(name: "accessmode"): XrmBase.OptionSetControl<systemuser_accessmode>;
            get(name: "address1_city"): XrmBase.StringControl;
            get(name: "address1_country"): XrmBase.StringControl;
            get(name: "address1_fax"): XrmBase.StringControl;
            get(name: "address1_line1"): XrmBase.StringControl;
            get(name: "address1_line2"): XrmBase.StringControl;
            get(name: "address1_line3"): XrmBase.StringControl;
            get(name: "address1_postalcode"): XrmBase.StringControl;
            get(name: "address1_stateorprovince"): XrmBase.StringControl;
            get(name: "address1_telephone1"): XrmBase.StringControl;
            get(name: "address1_telephone2"): XrmBase.StringControl;
            get(name: "address1_telephone3"): XrmBase.StringControl;
            get(name: "address2_city"): XrmBase.StringControl;
            get(name: "address2_country"): XrmBase.StringControl;
            get(name: "address2_line1"): XrmBase.StringControl;
            get(name: "address2_line2"): XrmBase.StringControl;
            get(name: "address2_line3"): XrmBase.StringControl;
            get(name: "address2_postalcode"): XrmBase.StringControl;
            get(name: "address2_stateorprovince"): XrmBase.StringControl;
            get(name: "businessunitid"): XrmBase.LookupControl<"businessunit">;
            get(name: "caltype"): XrmBase.OptionSetControl<systemuser_caltype>;
            get(name: "defaultmailbox"): XrmBase.LookupControl<"mailbox">;
            get(name: "domainname"): XrmBase.StringControl;
            get(name: "firstname"): XrmBase.StringControl;
            get(name: "homephone"): XrmBase.StringControl;
            get(name: "internalemailaddress"): XrmBase.StringControl;
            get(name: "invitestatuscode"): XrmBase.OptionSetControl<systemuser_invitestatuscode>;
            get(name: "lastname"): XrmBase.StringControl;
            get(name: "mobilealertemail"): XrmBase.StringControl;
            get(name: "mobilephone"): XrmBase.StringControl;
            get(name: "parentsystemuserid"): XrmBase.LookupControl<"systemuser">;
            get(name: "personalemailaddress"): XrmBase.StringControl;
            get(name: "positionid"): XrmBase.LookupControl<"position">;
            get(name: "preferredaddresscode"): XrmBase.OptionSetControl<systemuser_preferredaddresscode>;
            get(name: "preferredphonecode"): XrmBase.OptionSetControl<systemuser_preferredphonecode>;
            get(name: "queueid"): XrmBase.LookupControl<"queue">;
            get(name: "siteid"): XrmBase.LookupControl<"site">;
            get(name: "territoryid"): XrmBase.LookupControl<"territory">;
            get(name: "title"): XrmBase.StringControl;
            get(name: "WebResource_RecordWall"): XrmBase.WebResourceControl;
            get(name: "windowsliveid"): XrmBase.StringControl;
            get(name: string): undefined;
            get(): XrmBase.BaseControl[];
            get(index: number): XrmBase.BaseControl;
            get(chooser: (item: XrmBase.BaseControl, index: number) => boolean): XrmBase.BaseControl[];
        }
        interface Tabs extends XrmBase.TabCollectionBase {
            get(name: "tab_recordwall"): XrmBase.PageTab<Tabs.Tabrecordwall>;
            get(name: "general"): XrmBase.PageTab<Tabs.General>;
            get(name: "addresses"): XrmBase.PageTab<Tabs.Addresses>;
            get(name: string): undefined;
            get(): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
            get(index: number): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>;
            get(chooser: (item: XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>, index: number) => boolean): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
        }
    }
    interface Information extends XrmBase.PageBase<Information.Attributes, Information.Tabs, Information.Controls> {
        getAttribute(attributeName: "domainname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "windowsliveid"): XrmBase.StringAttribute;
        getAttribute(attributeName: "invitestatuscode"): XrmBase.OptionSetAttribute<systemuser_invitestatuscode>;
        getAttribute(attributeName: "firstname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_telephone1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "lastname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_telephone2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "title"): XrmBase.StringAttribute;
        getAttribute(attributeName: "homephone"): XrmBase.StringAttribute;
        getAttribute(attributeName: "internalemailaddress"): XrmBase.StringAttribute;
        getAttribute(attributeName: "mobilephone"): XrmBase.StringAttribute;
        getAttribute(attributeName: "personalemailaddress"): XrmBase.StringAttribute;
        getAttribute(attributeName: "preferredphonecode"): XrmBase.OptionSetAttribute<systemuser_preferredphonecode>;
        getAttribute(attributeName: "mobilealertemail"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_telephone3"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_fax"): XrmBase.StringAttribute;
        getAttribute(attributeName: "positionid"): XrmBase.LookupAttribute<"position">;
        getAttribute(attributeName: "parentsystemuserid"): XrmBase.LookupAttribute<"systemuser">;
        getAttribute(attributeName: "businessunitid"): XrmBase.LookupAttribute<"businessunit">;
        getAttribute(attributeName: "territoryid"): XrmBase.LookupAttribute<"territory">;
        getAttribute(attributeName: "siteid"): XrmBase.LookupAttribute<"site">;
        getAttribute(attributeName: "defaultmailbox"): XrmBase.LookupAttribute<"mailbox">;
        getAttribute(attributeName: "accessmode"): XrmBase.OptionSetAttribute<systemuser_accessmode>;
        getAttribute(attributeName: "caltype"): XrmBase.OptionSetAttribute<systemuser_caltype>;
        getAttribute(attributeName: "queueid"): XrmBase.LookupAttribute<"queue">;
        getAttribute(attributeName: "address1_line1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_stateorprovince"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_postalcode"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_line3"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_country"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address1_city"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address2_line1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address2_stateorprovince"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address2_line2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address2_postalcode"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address2_line3"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address2_country"): XrmBase.StringAttribute;
        getAttribute(attributeName: "address2_city"): XrmBase.StringAttribute;
        getAttribute(attributeName: "preferredaddresscode"): XrmBase.OptionSetAttribute<systemuser_preferredaddresscode>;
        getAttribute(attributeName: string): undefined;
        getControl(controlName: "WebResource_RecordWall"): XrmBase.WebResourceControl;
        getControl(controlName: "domainname"): XrmBase.StringControl;
        getControl(controlName: "windowsliveid"): XrmBase.StringControl;
        getControl(controlName: "invitestatuscode"): XrmBase.OptionSetControl<systemuser_invitestatuscode>;
        getControl(controlName: "firstname"): XrmBase.StringControl;
        getControl(controlName: "address1_telephone1"): XrmBase.StringControl;
        getControl(controlName: "lastname"): XrmBase.StringControl;
        getControl(controlName: "address1_telephone2"): XrmBase.StringControl;
        getControl(controlName: "title"): XrmBase.StringControl;
        getControl(controlName: "homephone"): XrmBase.StringControl;
        getControl(controlName: "internalemailaddress"): XrmBase.StringControl;
        getControl(controlName: "mobilephone"): XrmBase.StringControl;
        getControl(controlName: "personalemailaddress"): XrmBase.StringControl;
        getControl(controlName: "preferredphonecode"): XrmBase.OptionSetControl<systemuser_preferredphonecode>;
        getControl(controlName: "mobilealertemail"): XrmBase.StringControl;
        getControl(controlName: "address1_telephone3"): XrmBase.StringControl;
        getControl(controlName: "address1_fax"): XrmBase.StringControl;
        getControl(controlName: "positionid"): XrmBase.LookupControl<"position">;
        getControl(controlName: "parentsystemuserid"): XrmBase.LookupControl<"systemuser">;
        getControl(controlName: "businessunitid"): XrmBase.LookupControl<"businessunit">;
        getControl(controlName: "territoryid"): XrmBase.LookupControl<"territory">;
        getControl(controlName: "siteid"): XrmBase.LookupControl<"site">;
        getControl(controlName: "defaultmailbox"): XrmBase.LookupControl<"mailbox">;
        getControl(controlName: "accessmode"): XrmBase.OptionSetControl<systemuser_accessmode>;
        getControl(controlName: "caltype"): XrmBase.OptionSetControl<systemuser_caltype>;
        getControl(controlName: "queueid"): XrmBase.LookupControl<"queue">;
        getControl(controlName: "address1_line1"): XrmBase.StringControl;
        getControl(controlName: "address1_stateorprovince"): XrmBase.StringControl;
        getControl(controlName: "address1_line2"): XrmBase.StringControl;
        getControl(controlName: "address1_postalcode"): XrmBase.StringControl;
        getControl(controlName: "address1_line3"): XrmBase.StringControl;
        getControl(controlName: "address1_country"): XrmBase.StringControl;
        getControl(controlName: "address1_city"): XrmBase.StringControl;
        getControl(controlName: "address2_line1"): XrmBase.StringControl;
        getControl(controlName: "address2_stateorprovince"): XrmBase.StringControl;
        getControl(controlName: "address2_line2"): XrmBase.StringControl;
        getControl(controlName: "address2_postalcode"): XrmBase.StringControl;
        getControl(controlName: "address2_line3"): XrmBase.StringControl;
        getControl(controlName: "address2_country"): XrmBase.StringControl;
        getControl(controlName: "address2_city"): XrmBase.StringControl;
        getControl(controlName: "preferredaddresscode"): XrmBase.OptionSetControl<systemuser_preferredaddresscode>;
        getControl(controlName: string): undefined;
    }
}
