declare namespace Form.msdyn_workorder.Main {
    namespace WorkOrder {
        namespace Tabs {
            interface b8e326ee5c214a18ba55e3b56966c249 extends XrmBase.SectionCollectionBase {
                get(name: "{b14f3e67-e51b-4b3e-bb7f-a9cf0cf8dc17}"): XrmBase.PageSection;
                get(name: "f1tab_mainsettings_section_5"): XrmBase.PageSection;
                get(name: "tab_3_section_1"): XrmBase.PageSection;
                get(name: "tab_8_section_1"): XrmBase.PageSection;
                get(name: "{b8e326ee-5c21-4a18-ba55-e3b56966c249}_section_2"): XrmBase.PageSection;
                get(name: "{b8e326ee-5c21-4a18-ba55-e3b56966c249}_section_3"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface F1tabmainsettings extends XrmBase.SectionCollectionBase {
                get(name: "tab_7_section_1"): XrmBase.PageSection;
                get(name: "f1tab_mainsettings_section_2"): XrmBase.PageSection;
                get(name: "f1tab_mainsettings_section_3"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Tab5 extends XrmBase.SectionCollectionBase {
                get(name: "tab_5_section_2"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Tab6 extends XrmBase.SectionCollectionBase {
                get(name: "tab_6_section_2"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Tab7 extends XrmBase.SectionCollectionBase {
                get(name: "tab_7_section_1_2"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface F1tabadditionalsettings extends XrmBase.SectionCollectionBase {
                get(name: "f1tab_settings_section_address"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface Tab8 extends XrmBase.SectionCollectionBase {
                get(name: "tab_8_section_2"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface DeviceInsightsTab extends XrmBase.SectionCollectionBase {
                get(name: "DeviceInsightsSection"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
            interface F1tabrecordlog extends XrmBase.SectionCollectionBase {
                get(name: "tab_6_section_1"): XrmBase.PageSection;
                get(name: string): undefined;
                get(): XrmBase.PageSection[];
                get(index: number): XrmBase.PageSection;
                get(chooser: (item: XrmBase.PageSection, index: number) => boolean): XrmBase.PageSection[];
            }
        }
        interface Attributes extends XrmBase.AttributeCollectionBase {
            get(name: "createdby"): XrmBase.LookupAttribute<"systemuser">;
            get(name: "createdon"): XrmBase.DateAttribute;
            get(name: "modifiedby"): XrmBase.LookupAttribute<"systemuser">;
            get(name: "modifiedon"): XrmBase.DateAttribute;
            get(name: "msdyn_address1"): XrmBase.StringAttribute;
            get(name: "msdyn_address2"): XrmBase.StringAttribute;
            get(name: "msdyn_address3"): XrmBase.StringAttribute;
            get(name: "msdyn_addressname"): XrmBase.StringAttribute;
            get(name: "msdyn_agreement"): XrmBase.LookupAttribute<"msdyn_agreement">;
            get(name: "msdyn_billingaccount"): XrmBase.LookupAttribute<"account">;
            get(name: "msdyn_city"): XrmBase.StringAttribute;
            get(name: "msdyn_closedby"): XrmBase.LookupAttribute<"systemuser">;
            get(name: "msdyn_country"): XrmBase.StringAttribute;
            get(name: "msdyn_customerasset"): XrmBase.LookupAttribute<"msdyn_customerasset">;
            get(name: "msdyn_datewindowend"): XrmBase.DateAttribute;
            get(name: "msdyn_datewindowstart"): XrmBase.DateAttribute;
            get(name: "msdyn_estimatesubtotalamount"): XrmBase.NumberAttribute;
            get(name: "msdyn_instructions"): XrmBase.StringAttribute;
            get(name: "msdyn_iotalert"): XrmBase.LookupAttribute<"msdyn_iotalert">;
            get(name: "msdyn_latitude"): XrmBase.NumberAttribute;
            get(name: "msdyn_longitude"): XrmBase.NumberAttribute;
            get(name: "msdyn_mapcontrol"): XrmBase.StringAttribute;
            get(name: "msdyn_name"): XrmBase.StringAttribute;
            get(name: "msdyn_opportunityid"): XrmBase.LookupAttribute<"opportunity">;
            get(name: "msdyn_parentworkorder"): XrmBase.LookupAttribute<"msdyn_workorder">;
            get(name: "msdyn_postalcode"): XrmBase.StringAttribute;
            get(name: "msdyn_pricelist"): XrmBase.LookupAttribute<"pricelevel">;
            get(name: "msdyn_primaryincidentdescription"): XrmBase.StringAttribute;
            get(name: "msdyn_primaryincidentestimatedduration"): XrmBase.NumberAttribute;
            get(name: "msdyn_primaryincidenttype"): XrmBase.LookupAttribute<"msdyn_incidenttype">;
            get(name: "msdyn_priority"): XrmBase.LookupAttribute<"msdyn_priority">;
            get(name: "msdyn_reportedbycontact"): XrmBase.LookupAttribute<"contact">;
            get(name: "msdyn_serviceaccount"): XrmBase.LookupAttribute<"account">;
            get(name: "msdyn_servicerequest"): XrmBase.LookupAttribute<"incident">;
            get(name: "msdyn_serviceterritory"): XrmBase.LookupAttribute<"territory">;
            get(name: "msdyn_stateorprovince"): XrmBase.StringAttribute;
            get(name: "msdyn_substatus"): XrmBase.LookupAttribute<"msdyn_workordersubstatus">;
            get(name: "msdyn_subtotalamount"): XrmBase.NumberAttribute;
            get(name: "msdyn_supportcontact"): XrmBase.LookupAttribute<"bookableresource">;
            get(name: "msdyn_systemstatus"): XrmBase.OptionSetAttribute<msdyn_wosystemstatus>;
            get(name: "msdyn_taxable"): XrmBase.OptionSetAttribute<boolean>;
            get(name: "msdyn_taxcode"): XrmBase.LookupAttribute<"msdyn_taxcode">;
            get(name: "msdyn_timeclosed"): XrmBase.DateAttribute;
            get(name: "msdyn_timefrompromised"): XrmBase.DateAttribute;
            get(name: "msdyn_timegroup"): XrmBase.LookupAttribute<"msdyn_timegroup">;
            get(name: "msdyn_timetopromised"): XrmBase.DateAttribute;
            get(name: "msdyn_timewindowend"): XrmBase.DateAttribute;
            get(name: "msdyn_timewindowstart"): XrmBase.DateAttribute;
            get(name: "msdyn_totalamount"): XrmBase.NumberAttribute;
            get(name: "msdyn_totalsalestax"): XrmBase.NumberAttribute;
            get(name: "msdyn_workhourtemplate"): XrmBase.LookupAttribute<"msdyn_workhourtemplate">;
            get(name: "msdyn_worklocation"): XrmBase.OptionSetAttribute<msdyn_worklocation>;
            get(name: "msdyn_workordersummary"): XrmBase.StringAttribute;
            get(name: "msdyn_workordertype"): XrmBase.LookupAttribute<"msdyn_workordertype">;
            get(name: "ownerid"): XrmBase.LookupAttribute<"systemuser" | "team">;
            get(name: "transactioncurrencyid"): XrmBase.LookupAttribute<"transactioncurrency">;
            get(name: string): undefined;
            get(): XrmBase.Attribute<any>[];
            get(index: number): XrmBase.Attribute<any>;
            get(chooser: (item: XrmBase.Attribute<any>, index: number) => boolean): XrmBase.Attribute<any>[];
        }
        interface Controls extends XrmBase.ControlCollectionBase {
            get(name: "bookings"): XrmBase.SubGridControl<"bookableresourcebooking">;
            get(name: "createdby"): XrmBase.LookupControl<"systemuser">;
            get(name: "createdon"): XrmBase.DateControl;
            get(name: "Incidents_List"): XrmBase.SubGridControl<"msdyn_workorderincident">;
            get(name: "modifiedby"): XrmBase.LookupControl<"systemuser">;
            get(name: "modifiedon"): XrmBase.DateControl;
            get(name: "msdyn_address1"): XrmBase.StringControl;
            get(name: "msdyn_address2"): XrmBase.StringControl;
            get(name: "msdyn_address3"): XrmBase.StringControl;
            get(name: "msdyn_addressname"): XrmBase.StringControl;
            get(name: "msdyn_agreement"): XrmBase.LookupControl<"msdyn_agreement">;
            get(name: "msdyn_billingaccount"): XrmBase.LookupControl<"account">;
            get(name: "msdyn_city"): XrmBase.StringControl;
            get(name: "msdyn_closedby"): XrmBase.LookupControl<"systemuser">;
            get(name: "msdyn_country"): XrmBase.StringControl;
            get(name: "msdyn_customerasset"): XrmBase.LookupControl<"msdyn_customerasset">;
            get(name: "msdyn_datewindowend"): XrmBase.DateControl;
            get(name: "msdyn_datewindowstart"): XrmBase.DateControl;
            get(name: "msdyn_estimatesubtotalamount"): XrmBase.NumberControl;
            get(name: "msdyn_instructions"): XrmBase.StringControl;
            get(name: "msdyn_iotalert"): XrmBase.LookupControl<"msdyn_iotalert">;
            get(name: "msdyn_latitude"): XrmBase.NumberControl;
            get(name: "msdyn_longitude"): XrmBase.NumberControl;
            get(name: "msdyn_mapcontrol"): XrmBase.BaseControl;
            get(name: "msdyn_name"): XrmBase.StringControl;
            get(name: "msdyn_opportunityid"): XrmBase.LookupControl<"opportunity">;
            get(name: "msdyn_parentworkorder"): XrmBase.LookupControl<"msdyn_workorder">;
            get(name: "msdyn_postalcode"): XrmBase.StringControl;
            get(name: "msdyn_pricelist"): XrmBase.LookupControl<"pricelevel">;
            get(name: "msdyn_primaryincidentdescription"): XrmBase.StringControl;
            get(name: "msdyn_primaryincidentestimatedduration"): XrmBase.NumberControl;
            get(name: "msdyn_primaryincidenttype"): XrmBase.LookupControl<"msdyn_incidenttype">;
            get(name: "msdyn_priority"): XrmBase.LookupControl<"msdyn_priority">;
            get(name: "msdyn_reportedbycontact"): XrmBase.LookupControl<"contact">;
            get(name: "msdyn_serviceaccount"): XrmBase.LookupControl<"account">;
            get(name: "msdyn_servicerequest"): XrmBase.LookupControl<"incident">;
            get(name: "msdyn_serviceterritory"): XrmBase.LookupControl<"territory">;
            get(name: "msdyn_stateorprovince"): XrmBase.StringControl;
            get(name: "msdyn_substatus"): XrmBase.LookupControl<"msdyn_workordersubstatus">;
            get(name: "msdyn_subtotalamount"): XrmBase.NumberControl;
            get(name: "msdyn_supportcontact"): XrmBase.LookupControl<"bookableresource">;
            get(name: "msdyn_systemstatus"): XrmBase.OptionSetControl<msdyn_wosystemstatus>;
            get(name: "msdyn_taxable"): XrmBase.OptionSetControl<any>;
            get(name: "msdyn_taxcode"): XrmBase.LookupControl<"msdyn_taxcode">;
            get(name: "msdyn_timeclosed"): XrmBase.DateControl;
            get(name: "msdyn_timefrompromised"): XrmBase.DateControl;
            get(name: "msdyn_timegroup"): XrmBase.LookupControl<"msdyn_timegroup">;
            get(name: "msdyn_timetopromised"): XrmBase.DateControl;
            get(name: "msdyn_timewindowend"): XrmBase.BaseControl;
            get(name: "msdyn_timewindowstart"): XrmBase.BaseControl;
            get(name: "msdyn_totalamount"): XrmBase.NumberControl;
            get(name: "msdyn_totalsalestax"): XrmBase.NumberControl;
            get(name: "msdyn_workhourtemplate"): XrmBase.LookupControl<"msdyn_workhourtemplate">;
            get(name: "msdyn_worklocation"): XrmBase.OptionSetControl<msdyn_worklocation>;
            get(name: "msdyn_workordersummary"): XrmBase.StringControl;
            get(name: "msdyn_workordertype"): XrmBase.LookupControl<"msdyn_workordertype">;
            get(name: "notescontrol"): XrmBase.StringControl;
            get(name: "ownerid"): XrmBase.LookupControl<"systemuser" | "team">;
            get(name: "service_account_details"): XrmBase.BaseControl;
            get(name: "transactioncurrencyid"): XrmBase.LookupControl<"transactioncurrency">;
            get(name: "WebResource_msdyn_timewindowend"): XrmBase.WebResourceControl;
            get(name: "WebResource_msdyn_timewindowstart"): XrmBase.WebResourceControl;
            get(name: "workorderproductsgrid"): XrmBase.SubGridControl<"msdyn_workorderproduct">;
            get(name: "workorderservicesgrid"): XrmBase.SubGridControl<"msdyn_workorderservice">;
            get(name: "workorderservicetasksgrid"): XrmBase.SubGridControl<"msdyn_workorderservicetask">;
            get(name: string): undefined;
            get(): XrmBase.BaseControl[];
            get(index: number): XrmBase.BaseControl;
            get(chooser: (item: XrmBase.BaseControl, index: number) => boolean): XrmBase.BaseControl[];
        }
        interface Tabs extends XrmBase.TabCollectionBase {
            get(name: "{b8e326ee-5c21-4a18-ba55-e3b56966c249}"): XrmBase.PageTab<Tabs.b8e326ee5c214a18ba55e3b56966c249>;
            get(name: "f1tab_mainsettings"): XrmBase.PageTab<Tabs.F1tabmainsettings>;
            get(name: "tab_5"): XrmBase.PageTab<Tabs.Tab5>;
            get(name: "tab_6"): XrmBase.PageTab<Tabs.Tab6>;
            get(name: "tab_7"): XrmBase.PageTab<Tabs.Tab7>;
            get(name: "f1tab_additionalsettings"): XrmBase.PageTab<Tabs.F1tabadditionalsettings>;
            get(name: "tab_8"): XrmBase.PageTab<Tabs.Tab8>;
            get(name: "DeviceInsightsTab"): XrmBase.PageTab<Tabs.DeviceInsightsTab>;
            get(name: "f1tab_record_log"): XrmBase.PageTab<Tabs.F1tabrecordlog>;
            get(name: string): undefined;
            get(): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
            get(index: number): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>;
            get(chooser: (item: XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>, index: number) => boolean): XrmBase.PageTab<XrmBase.Collection<XrmBase.PageSection>>[];
        }
    }
    interface WorkOrder extends XrmBase.PageBase<WorkOrder.Attributes, WorkOrder.Tabs, WorkOrder.Controls> {
        getAttribute(attributeName: "msdyn_name"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_serviceaccount"): XrmBase.LookupAttribute<"account">;
        getAttribute(attributeName: "msdyn_billingaccount"): XrmBase.LookupAttribute<"account">;
        getAttribute(attributeName: "msdyn_systemstatus"): XrmBase.OptionSetAttribute<msdyn_wosystemstatus>;
        getAttribute(attributeName: "msdyn_substatus"): XrmBase.LookupAttribute<"msdyn_workordersubstatus">;
        getAttribute(attributeName: "msdyn_workordertype"): XrmBase.LookupAttribute<"msdyn_workordertype">;
        getAttribute(attributeName: "msdyn_pricelist"): XrmBase.LookupAttribute<"pricelevel">;
        getAttribute(attributeName: "msdyn_workhourtemplate"): XrmBase.LookupAttribute<"msdyn_workhourtemplate">;
        getAttribute(attributeName: "msdyn_workordersummary"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_taxable"): XrmBase.OptionSetAttribute<boolean>;
        getAttribute(attributeName: "msdyn_taxcode"): XrmBase.LookupAttribute<"msdyn_taxcode">;
        getAttribute(attributeName: "msdyn_primaryincidenttype"): XrmBase.LookupAttribute<"msdyn_incidenttype">;
        getAttribute(attributeName: "msdyn_primaryincidentdescription"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_primaryincidentestimatedduration"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "msdyn_customerasset"): XrmBase.LookupAttribute<"msdyn_customerasset">;
        getAttribute(attributeName: "msdyn_iotalert"): XrmBase.LookupAttribute<"msdyn_iotalert">;
        getAttribute(attributeName: "msdyn_estimatesubtotalamount"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "msdyn_subtotalamount"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "msdyn_totalsalestax"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "msdyn_totalamount"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "msdyn_priority"): XrmBase.LookupAttribute<"msdyn_priority">;
        getAttribute(attributeName: "msdyn_worklocation"): XrmBase.OptionSetAttribute<msdyn_worklocation>;
        getAttribute(attributeName: "msdyn_serviceterritory"): XrmBase.LookupAttribute<"territory">;
        getAttribute(attributeName: "transactioncurrencyid"): XrmBase.LookupAttribute<"transactioncurrency">;
        getAttribute(attributeName: "msdyn_instructions"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_reportedbycontact"): XrmBase.LookupAttribute<"contact">;
        getAttribute(attributeName: "msdyn_supportcontact"): XrmBase.LookupAttribute<"bookableresource">;
        getAttribute(attributeName: "msdyn_timefrompromised"): XrmBase.DateAttribute;
        getAttribute(attributeName: "msdyn_timetopromised"): XrmBase.DateAttribute;
        getAttribute(attributeName: "msdyn_datewindowstart"): XrmBase.DateAttribute;
        getAttribute(attributeName: "msdyn_datewindowend"): XrmBase.DateAttribute;
        getAttribute(attributeName: "msdyn_timewindowstart"): XrmBase.DateAttribute;
        getAttribute(attributeName: "msdyn_timewindowend"): XrmBase.DateAttribute;
        getAttribute(attributeName: "msdyn_timegroup"): XrmBase.LookupAttribute<"msdyn_timegroup">;
        getAttribute(attributeName: "msdyn_parentworkorder"): XrmBase.LookupAttribute<"msdyn_workorder">;
        getAttribute(attributeName: "msdyn_agreement"): XrmBase.LookupAttribute<"msdyn_agreement">;
        getAttribute(attributeName: "msdyn_opportunityid"): XrmBase.LookupAttribute<"opportunity">;
        getAttribute(attributeName: "msdyn_servicerequest"): XrmBase.LookupAttribute<"incident">;
        getAttribute(attributeName: "msdyn_addressname"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_stateorprovince"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_address1"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_postalcode"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_address2"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_country"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_address3"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_latitude"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "msdyn_city"): XrmBase.StringAttribute;
        getAttribute(attributeName: "msdyn_longitude"): XrmBase.NumberAttribute;
        getAttribute(attributeName: "msdyn_mapcontrol"): XrmBase.StringAttribute;
        getAttribute(attributeName: "createdby"): XrmBase.LookupAttribute<"systemuser">;
        getAttribute(attributeName: "createdon"): XrmBase.DateAttribute;
        getAttribute(attributeName: "modifiedby"): XrmBase.LookupAttribute<"systemuser">;
        getAttribute(attributeName: "modifiedon"): XrmBase.DateAttribute;
        getAttribute(attributeName: "msdyn_closedby"): XrmBase.LookupAttribute<"systemuser">;
        getAttribute(attributeName: "msdyn_timeclosed"): XrmBase.DateAttribute;
        getAttribute(attributeName: "ownerid"): XrmBase.LookupAttribute<"systemuser" | "team">;
        getAttribute(attributeName: string): undefined;
        getControl(controlName: "msdyn_name"): XrmBase.StringControl;
        getControl(controlName: "msdyn_serviceaccount"): XrmBase.LookupControl<"account">;
        getControl(controlName: "msdyn_billingaccount"): XrmBase.LookupControl<"account">;
        getControl(controlName: "msdyn_systemstatus"): XrmBase.OptionSetControl<msdyn_wosystemstatus>;
        getControl(controlName: "msdyn_substatus"): XrmBase.LookupControl<"msdyn_workordersubstatus">;
        getControl(controlName: "msdyn_workordertype"): XrmBase.LookupControl<"msdyn_workordertype">;
        getControl(controlName: "msdyn_pricelist"): XrmBase.LookupControl<"pricelevel">;
        getControl(controlName: "msdyn_workhourtemplate"): XrmBase.LookupControl<"msdyn_workhourtemplate">;
        getControl(controlName: "msdyn_workordersummary"): XrmBase.StringControl;
        getControl(controlName: "msdyn_taxable"): XrmBase.OptionSetControl<any>;
        getControl(controlName: "msdyn_taxcode"): XrmBase.LookupControl<"msdyn_taxcode">;
        getControl(controlName: "msdyn_primaryincidenttype"): XrmBase.LookupControl<"msdyn_incidenttype">;
        getControl(controlName: "msdyn_primaryincidentdescription"): XrmBase.StringControl;
        getControl(controlName: "msdyn_primaryincidentestimatedduration"): XrmBase.NumberControl;
        getControl(controlName: "msdyn_customerasset"): XrmBase.LookupControl<"msdyn_customerasset">;
        getControl(controlName: "msdyn_iotalert"): XrmBase.LookupControl<"msdyn_iotalert">;
        getControl(controlName: "msdyn_estimatesubtotalamount"): XrmBase.NumberControl;
        getControl(controlName: "msdyn_subtotalamount"): XrmBase.NumberControl;
        getControl(controlName: "msdyn_totalsalestax"): XrmBase.NumberControl;
        getControl(controlName: "msdyn_totalamount"): XrmBase.NumberControl;
        getControl(controlName: "notescontrol"): XrmBase.StringControl;
        getControl(controlName: "service_account_details"): XrmBase.BaseControl;
        getControl(controlName: "Incidents_List"): XrmBase.SubGridControl<"msdyn_workorderincident">;
        getControl(controlName: "bookings"): XrmBase.SubGridControl<"bookableresourcebooking">;
        getControl(controlName: "msdyn_priority"): XrmBase.LookupControl<"msdyn_priority">;
        getControl(controlName: "msdyn_worklocation"): XrmBase.OptionSetControl<msdyn_worklocation>;
        getControl(controlName: "msdyn_serviceterritory"): XrmBase.LookupControl<"territory">;
        getControl(controlName: "transactioncurrencyid"): XrmBase.LookupControl<"transactioncurrency">;
        getControl(controlName: "msdyn_instructions"): XrmBase.StringControl;
        getControl(controlName: "msdyn_reportedbycontact"): XrmBase.LookupControl<"contact">;
        getControl(controlName: "msdyn_supportcontact"): XrmBase.LookupControl<"bookableresource">;
        getControl(controlName: "msdyn_timefrompromised"): XrmBase.DateControl;
        getControl(controlName: "msdyn_timetopromised"): XrmBase.DateControl;
        getControl(controlName: "msdyn_datewindowstart"): XrmBase.DateControl;
        getControl(controlName: "msdyn_datewindowend"): XrmBase.DateControl;
        getControl(controlName: "WebResource_msdyn_timewindowstart"): XrmBase.WebResourceControl;
        getControl(controlName: "WebResource_msdyn_timewindowend"): XrmBase.WebResourceControl;
        getControl(controlName: "msdyn_timewindowstart"): XrmBase.BaseControl;
        getControl(controlName: "msdyn_timewindowend"): XrmBase.BaseControl;
        getControl(controlName: "msdyn_timegroup"): XrmBase.LookupControl<"msdyn_timegroup">;
        getControl(controlName: "msdyn_parentworkorder"): XrmBase.LookupControl<"msdyn_workorder">;
        getControl(controlName: "msdyn_agreement"): XrmBase.LookupControl<"msdyn_agreement">;
        getControl(controlName: "msdyn_opportunityid"): XrmBase.LookupControl<"opportunity">;
        getControl(controlName: "msdyn_servicerequest"): XrmBase.LookupControl<"incident">;
        getControl(controlName: "workorderproductsgrid"): XrmBase.SubGridControl<"msdyn_workorderproduct">;
        getControl(controlName: "workorderservicesgrid"): XrmBase.SubGridControl<"msdyn_workorderservice">;
        getControl(controlName: "workorderservicetasksgrid"): XrmBase.SubGridControl<"msdyn_workorderservicetask">;
        getControl(controlName: "msdyn_addressname"): XrmBase.StringControl;
        getControl(controlName: "msdyn_stateorprovince"): XrmBase.StringControl;
        getControl(controlName: "msdyn_address1"): XrmBase.StringControl;
        getControl(controlName: "msdyn_postalcode"): XrmBase.StringControl;
        getControl(controlName: "msdyn_address2"): XrmBase.StringControl;
        getControl(controlName: "msdyn_country"): XrmBase.StringControl;
        getControl(controlName: "msdyn_address3"): XrmBase.StringControl;
        getControl(controlName: "msdyn_latitude"): XrmBase.NumberControl;
        getControl(controlName: "msdyn_city"): XrmBase.StringControl;
        getControl(controlName: "msdyn_longitude"): XrmBase.NumberControl;
        getControl(controlName: "msdyn_mapcontrol"): XrmBase.BaseControl;
        getControl(controlName: "createdby"): XrmBase.LookupControl<"systemuser">;
        getControl(controlName: "createdon"): XrmBase.DateControl;
        getControl(controlName: "modifiedby"): XrmBase.LookupControl<"systemuser">;
        getControl(controlName: "modifiedon"): XrmBase.DateControl;
        getControl(controlName: "msdyn_closedby"): XrmBase.LookupControl<"systemuser">;
        getControl(controlName: "msdyn_timeclosed"): XrmBase.DateControl;
        getControl(controlName: "ownerid"): XrmBase.LookupControl<"systemuser" | "team">;
        getControl(controlName: string): undefined;
    }
}
